before_script: 
    - apt update -qy
    - apt install -y gfortran libblas-dev liblapack-dev 
    
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest pytest-cov mock
    - pip install pep8 python-coveralls
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

run:
    script:
        - make test
